version: 2
updates:
  - package-ecosystem: swift
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Europe/Zurich
    open-pull-requests-limit: 3
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Europe/Zurich
    open-pull-requests-limit: 3
    groups:
      actions:
        patterns: ["*"]
        update-types: [minor, patch]
