#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
TOTAL_MINUTES=28

# Configures a release machine for nitpick's signing ladder — the four
# prerequisites in docs/release.md "One-time setup": update-feed hosting
# (a public GitHub repo with one fixed 'updates' release, so Sparkle's
# enclosure URLs never change between versions), Developer ID certificate,
# notary credentials, and Sparkle EdDSA keypair. Hosting runs FIRST: its
# optional history rewrite hard-resets the worktree, which would discard
# uncommitted release.env values written by later stages.
#
# Re-runnable: every stage detects already-done state and skips itself.
# Secrets (app-specific password, Sparkle private key) live only in the
# login Keychain; scripts/release/release.env receives names and URLs.

cd "$(dirname "$0")/../.."
RELEASE_ENV="scripts/release/release.env"
ENV_FILE="$RELEASE_ENV"   # finish() reports writes against this file
GENERATE_KEYS=".build/artifacts/sparkle/Sparkle/bin/generate_keys"

# release.env keeps every value as `: "${KEY:=default}"` so environment
# overrides win when the release scripts source it. These helpers read and
# upsert the *default* in place — appending KEY=value lines (write_env)
# would silently break that contract.
release_env_get() (
  unset -v "$1" || true
  # shellcheck disable=SC1090
  . "$RELEASE_ENV"
  eval 'printf %s "${'"$1"':-}"'
)

release_env_set() {
  local key="$1" value="$2" tmp
  case "$value" in
    *[\"\$\`\\]*)
      warn "refusing to write $key: value contains \" \$ \` or \\"
      return 1 ;;
  esac
  tmp=$(mktemp)
  NEW_VALUE="$value" awk -v key="$key" '
    index($0, ": \"${" key ":=") == 1 {
      printf ": \"${%s:=%s}\"\n", key, ENVIRON["NEW_VALUE"]; found = 1; next
    }
    { print }
    END { exit found ? 0 : 3 }
  ' "$RELEASE_ENV" > "$tmp" || {
    rm -f "$tmp"; warn "no ': \"\${$key:=…}\"' line in $RELEASE_ENV"; return 1; }
  mv "$tmp" "$RELEASE_ENV"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$RELEASE_ENV"
}

# ask_default KEY "Prompt" DEFAULT — like ask, but the default comes from the
# caller (release.env values are not KEY=value lines the library can read).
ask_default() {
  local key="$1" prompt="$2" def="$3" input
  if [[ -n "$def" ]]; then
    printf '  %s%s%s %s[Enter keeps: %s]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$def" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" ]] && input="$def"
  printf -v "$key" '%s' "$input"
}

dev_id_identities() {
  security find-identity -v -p codesigning 2>/dev/null |
    sed -n 's/.*"\(Developer ID Application: [^"]*\)".*/\1/p' | sort -u
}

banner "nitpick release signing — one-time machine setup"

# ── Stage 1: public GitHub repo — hosting for downloads + updates ─────────
stage "Public GitHub repo — update-feed hosting" 8
say "Release zips and appcast.xml are published as assets of ONE fixed"
say "GitHub release (tag 'updates'), so Sparkle's enclosure URLs stay"
say "stable across versions. Per-version tags would break the static"
say "download prefix generate_appcast stamps into every enclosure."
if ! command -v gh >/dev/null 2>&1; then
  warn "GitHub CLI missing — install it: brew install gh"
  pause "Press Enter once gh is installed"
fi
until gh auth status >/dev/null 2>&1; do
  step "In another terminal: gh auth login"
  pause "Press Enter once authenticated"
done

# Publish safety: .scratch/ is the local issue tracker and .codegraph/ a
# machine index (AGENTS.md: local-only, no remote tracker). Neither may
# reach a public remote — the wizard refuses to push until git is clean of
# them. Order matters: untrack FIRST, so the files are untracked-ignored on
# disk before filter-repo's post-rewrite reset (which would otherwise
# delete the working copies of purged paths).
PUBLISH_OK=1
if git remote get-url origin >/dev/null 2>&1; then
  say "origin already set: $(git remote get-url origin)"
  if [[ -n "$(git ls-files .scratch .codegraph)" ]]; then
    warn ".scratch/ or .codegraph/ are tracked and a remote already exists —"
    warn "clean them up before the next push: git rm -r --cached .scratch .codegraph"
  fi
else
  TRACKED_LOCAL=()
  for p in .scratch .codegraph; do
    [[ -n "$(git ls-files "$p")" ]] && TRACKED_LOCAL+=("$p")
  done
  # filter-repo hard-resets the worktree after rewriting (verified: it
  # discards uncommitted changes to tracked files), and the untrack commit
  # must not sweep unrelated staged work — any cleaning therefore demands
  # a clean tracked worktree first. Untracked files are safe.
  if (( ${#TRACKED_LOCAL[@]} )) || [[ -n "$(git log --oneline -- .scratch .codegraph)" ]]; then
    while [[ -n "$(git status --porcelain --untracked-files=no)" ]]; do
      warn "uncommitted changes to tracked files — commit or stash them;"
      warn "the cleanup below would discard or sweep them."
      pause "Press Enter once 'git status' shows no tracked changes"
    done
  fi
  if (( ${#TRACKED_LOCAL[@]} )); then
    say "Tracked but local-only by convention: ${TRACKED_LOCAL[*]}"
    say "(.scratch/ = issue tracker + PRDs, .codegraph/ = machine index)."
    say "Untracking keeps the files on disk — they just leave git."
    if confirm "Untrack ${TRACKED_LOCAL[*]} and add them to .gitignore?"; then
      for p in "${TRACKED_LOCAL[@]}"; do
        grep -qxF "/$p/" .gitignore 2>/dev/null || printf '/%s/\n' "$p" >> .gitignore
      done
      git rm -r -q --cached "${TRACKED_LOCAL[@]}"
      git add .gitignore
      # Plain commit of the index — a pathspec-limited commit would re-add
      # the worktree copies of the rm --cached'd paths (verified). The
      # clean-worktree guard above keeps the commit isolated.
      git commit -q -m "Untrack local-only planning (.scratch/) and index (.codegraph/) state"
      say "Untracked and ignored; working copies untouched."
    else
      PUBLISH_OK=0
      warn "refusing to publish while local-only paths are tracked."
    fi
  fi
  if (( PUBLISH_OK )) && [[ -n "$(git log --oneline -- .scratch .codegraph)" ]]; then
    say "Past commits still contain those paths — a public clone could read"
    say "every PRD out of history. Nothing is published yet, so a rewrite is"
    say "free: no remote, no collaborators, hashes only change locally."
    until command -v git-filter-repo >/dev/null 2>&1; do
      step "In another terminal: brew install git-filter-repo"
      pause "Press Enter once installed"
    done
    BUNDLE="../nitpick-pre-publish-$(date +%Y%m%d-%H%M%S).bundle"
    git bundle create "$BUNDLE" --all
    say "Full backup written to $BUNDLE (delete it once satisfied)."
    if confirm "Purge .scratch/ + .codegraph/ from ALL history now?"; then
      git filter-repo --invert-paths --path .scratch --path .codegraph --force
      say "History rewritten; $(git log --oneline | wc -l | tr -d ' ') commits remain."
    else
      PUBLISH_OK=0
      warn "refusing to publish with planning docs readable in history."
    fi
  fi
  if (( PUBLISH_OK )); then
    ask_default REPO_NAME "Repository name:" "nitpick"
    if confirm "Create PUBLIC repo '$REPO_NAME' and push branch main?"; then
      gh repo create "$REPO_NAME" --public --source . --remote origin --push
    else
      PUBLISH_OK=0
    fi
  fi
  if (( ! PUBLISH_OK )); then
    SKIPPED+=("public repo + feed/download URLs — nothing was pushed; re-run this wizard when ready")
  fi
fi
if git remote get-url origin >/dev/null 2>&1; then
  NWO="$(gh repo view --json nameWithOwner -q .nameWithOwner)"
  if gh release view updates >/dev/null 2>&1; then
    say "Fixed 'updates' release already exists."
  else
    say "Creating the fixed 'updates' release (prerelease — never shown as Latest)…"
    gh release create updates --prerelease --title "Update feed" \
      --notes "Hosts appcast.xml and the release zips for Sparkle auto-updates. Do not delete assets: installed copies fetch them from here."
  fi
  BASE="https://github.com/$NWO/releases/download/updates"
  release_env_set NITPICK_FEED_URL "$BASE/appcast.xml"
  release_env_set NITPICK_DOWNLOAD_URL_PREFIX "$BASE"
fi

# ── Stage 2: Developer ID Application certificate ─────────────────────────
stage "Developer ID Application certificate" 10
say "Apps shared outside the App Store are signed with a 'Developer ID"
say "Application' certificate (Apple Development / Distribution won't do)."
IDENTITY="$(dev_id_identities | head -n1 || true)"
if [[ -n "$IDENTITY" ]]; then
  say "Already in your Keychain — nothing to create:"
  note "$(dev_id_identities)"
else
  say "None in your Keychain yet. Easiest path — Xcode (you must hold the"
  say "Account Holder role on your paid team):"
  step "Xcode → Settings… (⌘,) → Accounts tab."
  step "Select your Apple ID, then your paid team."
  step "Manage Certificates… → '+' (bottom-left) → 'Developer ID Application'."
  say ""
  say "If Xcode doesn't offer that entry, use the developer portal:"
  open_url "https://developer.apple.com/account/resources/certificates/add"
  step "Choose 'Developer ID Application' (default G2 Sub-CA profile is fine)."
  step "It asks for a CSR: Keychain Access → Certificate Assistant →"
  step "Request a Certificate from a Certificate Authority… → save to disk."
  step "Upload the CSR, download the .cer, double-click to install it."
  while [[ -z "$IDENTITY" ]]; do
    pause "Press Enter once the certificate is installed"
    IDENTITY="$(dev_id_identities | head -n1 || true)"
    if [[ -z "$IDENTITY" ]]; then
      warn "still no 'Developer ID Application' identity — did it land in the login Keychain?"
    fi
  done
  say "Detected: $IDENTITY"
fi
ask_default NITPICK_SIGNING_IDENTITY "Signing identity:" "$IDENTITY"
release_env_set NITPICK_SIGNING_IDENTITY "$NITPICK_SIGNING_IDENTITY"
TEAM_ID="$(printf '%s' "$NITPICK_SIGNING_IDENTITY" |
  sed -n 's/.*(\([A-Z0-9]\{10\}\))$/\1/p')"

# ── Stage 3: notary credentials ───────────────────────────────────────────
stage "Notary credentials" 5
NOTARY_PROFILE="$(release_env_get NITPICK_NOTARY_PROFILE)"
if xcrun notarytool history --keychain-profile "$NOTARY_PROFILE" >/dev/null 2>&1; then
  say "Keychain profile '$NOTARY_PROFILE' already authenticates — nothing to do."
else
  say "Notarization authenticates with an app-specific password (never your"
  say "real Apple ID password). Credentials go into the login Keychain only."
  open_url "https://account.apple.com/account/manage"
  step "Sign in → 'Sign-In and Security' → 'App-Specific Passwords'."
  step "Generate one (name it e.g. 'nitpick notary') and copy the"
  step "xxxx-xxxx-xxxx-xxxx value — it is shown only once."
  while :; do
    ask NOTARY_APPLE_ID "Apple ID (email):"
    ask_default NOTARY_TEAM_ID "Team ID:" "$TEAM_ID"
    ask_secret NOTARY_PASSWORD "App-specific password:"
    say "Storing credentials as profile '$NOTARY_PROFILE'…"
    if xcrun notarytool store-credentials "$NOTARY_PROFILE" \
        --apple-id "$NOTARY_APPLE_ID" --team-id "$NOTARY_TEAM_ID" \
        --password "$NOTARY_PASSWORD"; then
      break
    fi
    warn "store-credentials failed — typo in the password or team ID? Retrying."
  done
  say "Validating against the notary service…"
  if xcrun notarytool history --keychain-profile "$NOTARY_PROFILE" >/dev/null; then
    say "Notary profile '$NOTARY_PROFILE' works."
  else
    warn "profile stored but the notary service rejected it — check Apple ID/team."
    exit 1
  fi
fi

# ── Stage 4: Sparkle EdDSA keypair ────────────────────────────────────────
stage "Sparkle update-signing key (EdDSA)" 3
if [[ ! -x "$GENERATE_KEYS" ]]; then
  say "Sparkle's tools aren't resolved yet — running swift package resolve…"
  swift package resolve
fi
if PUBKEY="$("$GENERATE_KEYS" -p 2>/dev/null)"; then
  say "Sparkle signing key already in the Keychain."
else
  say "Generating the EdDSA keypair (private key → login Keychain)…"
  "$GENERATE_KEYS" >/dev/null
  PUBKEY="$("$GENERATE_KEYS" -p)"
fi
say "Public key: $PUBKEY"
release_env_set NITPICK_ED_PUBLIC_KEY "$PUBKEY"
say ""
warn "Back up the PRIVATE key: losing it strands every installed copy on"
warn "its current version — no future update would verify."
if confirm "Export a private-key backup now?"; then
  ask_default BACKUP_PATH "Backup file path:" "$HOME/Documents/nitpick-sparkle-ed25519.key"
  BACKUP_PATH="${BACKUP_PATH/#\~/$HOME}"
  if "$GENERATE_KEYS" -x "$BACKUP_PATH"; then
    say "Exported to $BACKUP_PATH."
    warn "It is the raw private key — move it to a password manager or"
    warn "encrypted disk. Never commit it, never upload it."
  else
    warn "export failed (destination exists?) — export by hand later."
    SKIPPED+=("Sparkle private-key backup ($GENERATE_KEYS -x <file>)")
  fi
else
  SKIPPED+=("Sparkle private-key backup ($GENERATE_KEYS -x <file>)")
fi

# ── Stage 5: readiness check ──────────────────────────────────────────────
stage "Readiness check" 2
OK=1
check() {
  local label="$1"; shift
  if "$@" >/dev/null 2>&1; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$label"
  else
    printf '  %s✗%s %s\n' "$RED" "$RESET" "$label"
    OK=0
  fi
}
check_identity() {
  local id; id="$(release_env_get NITPICK_SIGNING_IDENTITY)"
  [[ -n "$id" ]] && security find-identity -v -p codesigning | grep -qF "\"$id\""
}
check_notary() {
  xcrun notarytool history \
    --keychain-profile "$(release_env_get NITPICK_NOTARY_PROFILE)"
}
check_edkey() {
  local pub; pub="$(release_env_get NITPICK_ED_PUBLIC_KEY)"
  [[ -n "$pub" ]] && [[ "$("$GENERATE_KEYS" -p)" == "$pub" ]]
}
check_urls() {
  [[ "$(release_env_get NITPICK_FEED_URL)" == https://* ]] &&
    [[ "$(release_env_get NITPICK_DOWNLOAD_URL_PREFIX)" == https://* ]]
}
check "Developer ID identity in Keychain matches release.env" check_identity
check "notary profile authenticates against Apple" check_notary
check "Sparkle private key in Keychain matches NITPICK_ED_PUBLIC_KEY" check_edkey
check "feed + download URLs configured (https)" check_urls
say ""
if (( OK )); then
  say "Ready. Cut and publish a release:"
  note "  make release VERSION=1.0.0 BUILD=1"
  note "  make publish VERSION=1.0.0 BUILD=1"
  say ""
  say "release.env changed — commit it so the config is versioned."
else
  warn "some checks failed — fix the ✗ lines above or re-run this wizard;"
  warn "completed stages skip themselves."
fi

finish
